import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface AuditSubmission {
  id: string;
  branchName: string;
  branchNameAr: string;
  auditorName: string;
  auditorNameAr: string;
  date: string;
  scores: Record<number, { score: number; note: string; photo?: string }>;
  totalScore: number;
  percentage: number;
  actionItems: { point: string; action: string; responsible: string; deadline: string }[];
  emailList: string[];
}

export function generatePDF(submission: AuditSubmission): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFillColor(34, 139, 34); // Green color
  doc.rect(0, 0, pageWidth, 30, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Green Cafe Audit Report', pageWidth / 2, 12, { align: 'center' });
  doc.setFontSize(12);
  doc.text('تقرير تدقيق جرين كافيه', pageWidth / 2, 20, { align: 'center' });

  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  // Branch & Auditor Info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  
  const infoY = 40;
  doc.text('Branch / الفرع:', 14, infoY);
  doc.setFont('helvetica', 'normal');
  doc.text(submission.branchName, 50, infoY);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Auditor / المدقق:', 14, infoY + 8);
  doc.setFont('helvetica', 'normal');
  doc.text(submission.auditorName, 50, infoY + 8);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Date / التاريخ:', 14, infoY + 16);
  doc.setFont('helvetica', 'normal');
  doc.text(submission.date, 50, infoY + 16);

  // Score Summary
  doc.setFillColor(240, 240, 240);
  doc.rect(14, infoY + 24, pageWidth - 28, 25, 'F');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(`Total Score / النتيجة الإجمالية: ${submission.totalScore}/100`, pageWidth / 2, infoY + 35, { align: 'center' });
  
  doc.setFontSize(12);
  const scoreColor = submission.percentage >= 80 ? [34, 139, 34] : submission.percentage >= 60 ? [255, 165, 0] : [220, 20, 60];
  doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  doc.text(`${submission.percentage}%`, pageWidth / 2, infoY + 45, { align: 'center' });
  
  doc.setTextColor(0, 0, 0);

  // Detailed Scores Table
  const tableData: string[][] = [];
  
  const scoreEntries = Object.entries(submission.scores);
  for (const cat of scoreEntries) {
    if (cat[1] && cat[1].score >= 0) {
      tableData.push([
        `Q${cat[0]}`,
        cat[1].score.toString(),
        cat[1].note || '-'
      ]);
    }
  }

  autoTable(doc, {
    startY: infoY + 55,
    head: [['#', 'Score', 'Notes / ملاحظات']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [34, 139, 34] },
    styles: { fontSize: 9 },
  });

  // Action Plan
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  
  if (submission.actionItems.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Action Plan / خطة الإجراءات', 14, finalY);
    
    const actionData = submission.actionItems.map(item => [
      item.point,
      item.action,
      item.responsible,
      item.deadline
    ]);

    autoTable(doc, {
      startY: finalY + 5,
      head: [['Issue / المشكلة', 'Action / الإجراء', 'Responsible / المسؤول', 'Deadline / الموعد']],
      body: actionData,
      theme: 'grid',
      headStyles: { fillColor: [220, 53, 69] },
      styles: { fontSize: 8 },
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
    doc.text('Generated by Green Cafe Audit System', pageWidth / 2, doc.internal.pageSize.getHeight() - 5, { align: 'center' });
  }

  return doc;
}

export function generatePDFBlob(submission: AuditSubmission): Blob {
  const doc = generatePDF(submission);
  return doc.output('blob');
}
